SQL requests
Razorr1996/dbp-python-postgres-train pull request #1
Opened 2023-09-04 08:42 UTC by Razorr1996

2023-09-09 20:21 UTC, aleksandr-semenov-dbp requested changes

2023-09-09 20:21 UTC, aleksandr-semenov-dbp commented on sql_employees/tasks/1_employees_emails.sql
> +   OR email NOT LIKE '%dualbootpartners.com';
подходит intruder@fake-dualbootpartnes.com

2023-09-09 23:27 UTC, Razorr1996 commented on sql_employees/tasks/1_employees_emails.sql
> +   OR email NOT LIKE '%dualbootpartners.com';
Regexp fixed

2023-09-11 07:03 UTC, aleksandr-semenov-dbp approved these changes

2023-09-11 07:40 UTC, merged